org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

mod_id=yeetusexperimentus
archives_base_name=yeetusexperimentus
mod_version=99.0.0
maven_group=com.sunekaer.mods

curseforge_id=635427
modrinth_id=HaaH232J

# Dependencies
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)

neoforge_version=26.1.0.8-beta
neoforge_version_range=[26.1,27.0)

fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1
